apiVersion: v1
kind: Service
metadata:
  name: mysql-services
  namespace: devops-app
  labels:
    app.kubernetes.io/name: mysql
    app.kubernetes.io/instance: bucketlist
    app.kubernetes.io/component: database
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: mysql
    app.kubernetes.io/instance: bucketlist
  ports:
    - name: mysql
      port: 3306
      targetPort: mysql
      protocol: TCP
